"""Aggregate per-run swarm simulator outputs into a tidy table + TeX summary.

Reads `outputs/swarm_results/*.json` (one per (policy, fleet, workload, seed)
run) and produces:
  - `outputs/swarm_results/aggregate.csv` — tidy long-format table.
  - `outputs/tables/swarm_main.tex` — mean +/- std P99 + SLO attainment + churn
    grouped by (policy x workload x fleet_size).

The aggregation is deterministic so it can be re-run idempotently and pinned
as a DVC stage downstream.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path
from statistics import mean, pstdev

ROOT = Path(__file__).resolve().parents[1]
RES_DIR = ROOT / "outputs" / "swarm_results"
TAB_DIR = ROOT / "outputs" / "tables"
TAB_DIR.mkdir(parents=True, exist_ok=True)


def load_runs() -> list[dict]:
    runs = []
    for path in sorted(RES_DIR.glob("*.json")):
        if path.name == "summary.json":
            continue
        try:
            with path.open() as fh:
                runs.append(json.load(fh))
        except Exception:
            continue
    return runs


def write_csv(runs: list[dict]) -> Path:
    out = RES_DIR / "aggregate.csv"
    cols = [
        "policy_name",
        "dataset_name",
        "fleet_size",
        "seed",
        "n_requests_total",
        "n_requests_completed",
        "n_requests_rejected",
        "rejection_rate",
        "p50_latency_ms",
        "p95_latency_ms",
        "p99_latency_ms",
        "mean_latency_ms",
        "slo_attainment",
        "claim_count",
        "release_count",
        "wall_clock_seconds",
    ]
    with out.open("w") as fh:
        fh.write(",".join(cols) + "\n")
        for r in runs:
            fh.write(",".join(str(r.get(c, "")) for c in cols) + "\n")
    return out


def group_stats(runs: list[dict]) -> dict:
    groups: dict[tuple, list[dict]] = defaultdict(list)
    for r in runs:
        key = (r["policy_name"], r["dataset_name"], r["fleet_size"])
        groups[key].append(r)
    out: dict[tuple, dict] = {}
    for key, items in groups.items():
        out[key] = {
            "n": len(items),
            "p99_mean": mean(x["p99_latency_ms"] for x in items),
            "p99_std": pstdev(x["p99_latency_ms"] for x in items)
            if len(items) > 1
            else 0.0,
            "p95_mean": mean(x["p95_latency_ms"] for x in items),
            "p95_std": pstdev(x["p95_latency_ms"] for x in items)
            if len(items) > 1
            else 0.0,
            "slo_mean": mean(x["slo_attainment"] for x in items),
            "slo_std": pstdev(x["slo_attainment"] for x in items)
            if len(items) > 1
            else 0.0,
            "rej_mean": mean(x["rejection_rate"] for x in items),
            "churn_mean": mean(x["claim_count"] + x["release_count"] for x in items),
            "churn_std": pstdev(x["claim_count"] + x["release_count"] for x in items)
            if len(items) > 1
            else 0.0,
        }
    return out


def write_tex(stats: dict) -> Path:
    fleets = sorted({k[2] for k in stats})
    workloads = sorted({k[1] for k in stats})
    policies = ["reactive", "fd_dsp", "oracle"]
    out = TAB_DIR / "swarm_main.tex"
    with out.open("w") as fh:
        fh.write("% auto-generated by pipeline/aggregate_swarm.py — do not edit\n")
        fh.write("\\begin{tabular}{llrrrr}\n\\toprule\n")
        fh.write("Workload & Fleet & Policy & P99 (ms) & SLO attainment & Churn \\\\\n")
        fh.write("\\midrule\n")
        for w in workloads:
            for n in fleets:
                for p in policies:
                    short_p = {
                        "reactive": "Reactive",
                        "fd_dsp": "FD-DSP",
                        "oracle": "Oracle",
                    }[p]
                    matched = None
                    for k, v in stats.items():
                        if k[1] == w and k[2] == n and k[0].startswith(p):
                            matched = v
                            break
                    if matched is None:
                        continue
                    fh.write(
                        f"{w} & {n} & {short_p} & "
                        f"{matched['p99_mean']:.1f} $\\pm$ {matched['p99_std']:.1f} & "
                        f"{matched['slo_mean']*100:.1f}\\% $\\pm$ {matched['slo_std']*100:.1f} & "
                        f"{matched['churn_mean']:.1f} $\\pm$ {matched['churn_std']:.1f} \\\\\n"
                    )
                fh.write("\\midrule\n")
        fh.write("\\bottomrule\n\\end{tabular}\n")
    return out


def main():
    runs = load_runs()
    print(f"loaded {len(runs)} runs from {RES_DIR}")
    csv = write_csv(runs)
    print(f"wrote {csv}")
    stats = group_stats(runs)
    tex = write_tex(stats)
    print(f"wrote {tex}")
    print("\n=== summary stats ===")
    for key in sorted(stats):
        s = stats[key]
        print(
            f"  {key[0]:30s} {key[1]:18s} n={key[2]:3d}  P99={s['p99_mean']:8.1f}+-{s['p99_std']:6.1f}  "
            f"SLO={s['slo_mean']*100:5.1f}% rej={s['rej_mean']*100:5.1f}% churn={s['churn_mean']:5.1f}"
        )


if __name__ == "__main__":
    main()
