"""Aggregate FD-DSP-Auto and Reactive runs into a side-by-side comparison
table for the §swarm-eval:autotune subsection of the paper.

Reads from `outputs/swarm_results_auto/` (auto-tune sweep) and from
`outputs/swarm_results/` (vanilla reactive sweep), groups by
(dataset, fleet_size, policy_name), and emits
`outputs/tables/swarm_autotune.tex`.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path
from statistics import mean, pstdev

ROOT = Path(__file__).resolve().parents[1]
AUTO_DIR = ROOT / "outputs" / "swarm_results_auto"
BASE_DIR = ROOT / "outputs" / "swarm_results"
TAB_DIR = ROOT / "outputs" / "tables"
TAB_DIR.mkdir(parents=True, exist_ok=True)


def load_runs(directory: Path) -> list[dict]:
    runs = []
    for path in sorted(directory.glob("*.json")):
        if path.name == "summary.json":
            continue
        try:
            with path.open() as fh:
                runs.append(json.load(fh))
        except Exception:
            continue
    return runs


def group_stats(runs: list[dict], policy_filter: str | None = None) -> dict:
    groups: dict[tuple, list[dict]] = defaultdict(list)
    for r in runs:
        if policy_filter is not None and not r["policy_name"].startswith(policy_filter):
            continue
        key = (r["dataset_name"], r["fleet_size"])
        groups[key].append(r)
    out: dict[tuple, dict] = {}
    for key, items in groups.items():
        out[key] = {
            "n": len(items),
            "p99_mean": mean(x["p99_latency_ms"] for x in items),
            "p99_std": pstdev(x["p99_latency_ms"] for x in items)
            if len(items) > 1
            else 0.0,
            "slo_mean": mean(x["slo_attainment"] for x in items),
            "slo_std": pstdev(x["slo_attainment"] for x in items)
            if len(items) > 1
            else 0.0,
            "rej_mean": mean(x["rejection_rate"] for x in items),
            "churn_mean": mean(x["claim_count"] + x["release_count"] for x in items),
            "churn_std": pstdev(x["claim_count"] + x["release_count"] for x in items)
            if len(items) > 1
            else 0.0,
        }
    return out


def write_tex(reactive: dict, autotune: dict) -> Path:
    fleets = sorted({k[1] for k in autotune})
    workloads = sorted({k[0] for k in autotune})
    out = TAB_DIR / "swarm_autotune.tex"
    with out.open("w") as fh:
        fh.write("% auto-generated by pipeline/aggregate_swarm_autotune.py\n")
        fh.write("\\begin{tabular}{llrrrr}\n\\toprule\n")
        fh.write("Workload & Fleet & Policy & P99 (ms) & SLO attainment & Churn \\\\\n")
        fh.write("\\midrule\n")
        for w in workloads:
            for n in fleets:
                for label, src in (("Reactive", reactive), ("FD-DSP-Auto", autotune)):
                    stat = src.get((w, n))
                    if stat is None:
                        continue
                    fh.write(
                        f"{w} & {n} & {label} & "
                        f"{stat['p99_mean']:.1f} $\\pm$ {stat['p99_std']:.1f} & "
                        f"{stat['slo_mean']*100:.1f}\\% $\\pm$ {stat['slo_std']*100:.1f} & "
                        f"{stat['churn_mean']:.1f} $\\pm$ {stat['churn_std']:.1f} \\\\\n"
                    )
                fh.write("\\midrule\n")
        fh.write("\\bottomrule\n\\end{tabular}\n")
    return out


def main():
    reactive_runs = load_runs(BASE_DIR)
    auto_runs = load_runs(AUTO_DIR)
    reactive_stats = group_stats(reactive_runs, policy_filter="reactive")
    auto_stats = group_stats(auto_runs)
    out = write_tex(reactive_stats, auto_stats)
    print(f"wrote {out}")
    print("\n=== side-by-side summary ===")
    keys = sorted(set(reactive_stats) | set(auto_stats))
    for key in keys:
        r = reactive_stats.get(key)
        a = auto_stats.get(key)
        print(f"  {key[0]:18s} n={key[1]:3d}")
        for label, s in (("  reactive", r), ("  autotune", a)):
            if s is None:
                print(f"    {label:12s} —")
            else:
                print(
                    f"    {label:12s} P99={s['p99_mean']:7.1f}±{s['p99_std']:6.1f}  "
                    f"SLO={s['slo_mean']*100:5.1f}%  rej={s['rej_mean']*100:5.1f}%  churn={s['churn_mean']:5.1f}"
                )


if __name__ == "__main__":
    main()
