"""Build a paper-ready appendix table summarising every pipeline phase
recorded in outputs/runlog.jsonl.

This is the audit trail that lets a Computer Networks reviewer say
``ok, I see exactly which phases were run, how long they took, and
the git commit each ran on''.  The table is auto-generated and
re-runnable; refreshing it is one command::

    python3 pipeline/build_appendix_runlog.py

Output:
  paper/tables/appendix_runlog.tex
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

from src.utils.runlog import list_phases, PhaseTimer

OUT = Path("paper/tables")


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    rows = list_phases()
    if not rows:
        print("(no runlog yet)")
        return
    # Dedupe: keep latest entry per phase name
    by_phase: dict = {}
    for r in rows:
        by_phase[r["phase"]] = r
    rows = sorted(by_phase.values(), key=lambda x: x.get("start_utc", ""))

    total_s = sum(r["elapsed_seconds"] for r in rows)
    total_human = (
        f"{total_s/3600:.2f}~h" if total_s >= 3600 else f"{total_s/60:.1f}~min"
    )

    lines = [
        "% auto-generated by pipeline/build_appendix_runlog.py",
        r"\begin{table}[t]",
        r"\centering\small",
        r"\caption{Pipeline execution provenance (every phase, latest "
        r"execution).  Total wall-clock: "
        + total_human
        + r".  Re-derive with \texttt{python3 pipeline/run\_q1\_stage\_a.py}"
        r" followed by \texttt{stage\_c}.}",
        r"\label{tab:runlog}",
        r"\begin{tabular}{l l r}",
        r"\toprule",
        r"phase & status & elapsed \\",
        r"\midrule",
    ]
    for r in rows:
        phase = r["phase"].replace("_", r"\_")
        status = r["status"]
        elapsed = r["elapsed_human"]
        lines.append(f"{phase} & {status} & {elapsed} \\\\")
    lines += [
        r"\midrule",
        f"\\textbf{{total}} & & \\textbf{{{total_human}}} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
    ]
    out = OUT / "appendix_runlog.tex"
    out.write_text("\n".join(lines))
    print(f"wrote {out}  ({len(rows)} phases, total {total_human})")


if __name__ == "__main__":
    with PhaseTimer(
        "build_appendix_runlog", notes="paper appendix: phase-level provenance table"
    ) as t:
        main()
        t.add_output("tex", str(OUT / "appendix_runlog.tex"))
