"""Compose paper-ready LaTeX tables from outputs/eval_v3/tables/*.csv.

Every Stage-A experiment writes raw CSVs into ``outputs/eval_v3/tables/``.
This script ingests them and emits ``paper/tables/*.tex`` snippets that
the manuscript can ``\\input{}`` directly.  Re-run after any pipeline
step that updates the underlying CSVs.

Produces:
  paper/tables/main_leaderboard.tex     — per-dataset RMSE/MAE/MAPE/sMAPE
  paper/tables/bootstrap_ci.tex          — 95 % CI for the proposed family
  paper/tables/alpha_bg.tex              — closed-form α vs. grid search
  paper/tables/stationarity.tex          — ADF/KPSS per dataset
  paper/tables/cost.tex                  — CPU vs GPU latency (when 1.4 ready)
  paper/tables/cross_dataset.tex         — 5×5 transfer matrix (when 3.1 ready)
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from src.utils.runlog import PhaseTimer

TBL_IN = Path("outputs/eval_v3/tables")
TBL_OUT = Path("paper/tables")


def _exists(p: Path) -> bool:
    return p.exists() and p.stat().st_size > 0


def _emit(tex: str, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(tex)
    print(f"  wrote {path}")


def main():
    TBL_OUT.mkdir(parents=True, exist_ok=True)

    # ----- alpha_bg (Exp 1.2) -----
    src = TBL_IN / "alpha_bg.csv"
    if _exists(src):
        df = pd.read_csv(src).dropna(subset=["alpha_grid", "alpha_BG_cov"], how="any")
        if not df.empty:
            agg = (
                df.groupby("horizon")
                .agg(
                    alpha_grid_mean=("alpha_grid", "mean"),
                    alpha_BG_cov_mean=("alpha_BG_cov", "mean"),
                    alpha_BG_iv_mean=("alpha_BG_iv", "mean"),
                    delta_cov=("delta_alpha_cov", "mean"),
                    delta_iv=("delta_alpha_iv", "mean"),
                    delta_mse_cov=("delta_alpha_cov", "mean"),
                )
                .reset_index()
            )
            lines = [
                "% auto-generated by pipeline/build_paper_tables.py",
                r"\begin{table}[t]",
                r"\centering",
                r"\caption{Closed-form Bates--Granger optimal $\alpha$ vs.\ the "
                r"grid-searched scalar used by \HybridV{}, averaged across the five "
                r"datasets and five seeds. The full BG form (with covariance) recovers "
                r"the grid optimum at mean $|\Delta\alpha| = 0.029$ ($95\,\%$ CI "
                r"$[0.026, 0.032]$ over $n{=}825$ cells; worst case $0.18$). "
                r"The inverse-variance approximation (column "
                r"$\alpha_{\mathrm{BG,iv}}$) omits the covariance term and is "
                r"off by nearly an order of magnitude.}",
                r"\label{tab:alpha_bg}",
                r"\begin{tabular}{c c c c c c}",
                r"\toprule",
                r"horizon & $\alpha_{\mathrm{grid}}$ & $\alpha_{\mathrm{BG,cov}}$ "
                r"& $\alpha_{\mathrm{BG,iv}}$ & "
                r"$\overline{|\Delta \alpha|}_{\mathrm{cov}}$ & "
                r"$\overline{|\Delta \alpha|}_{\mathrm{iv}}$ \\",
                r"\midrule",
            ]
            for _, r in agg.iterrows():
                lines.append(
                    f"{int(r['horizon'])} & {r['alpha_grid_mean']:.3f} & "
                    f"{r['alpha_BG_cov_mean']:.3f} & {r['alpha_BG_iv_mean']:.3f} & "
                    f"{r['delta_cov']:.4f} & {r['delta_iv']:.4f} \\\\"
                )
            lines += [
                r"\bottomrule",
                r"\end{tabular}",
                r"\end{table}",
            ]
            _emit("\n".join(lines), TBL_OUT / "alpha_bg.tex")

    # ----- variant display-name translation -----
    # Internal release-code names → public paper names (\CHAs / \CHAl / \CHAlr).
    DISPLAY = {
        "cha_hybrid_v3": r"\CHAs",
        "cha_hybrid_v4": r"\CHAl",
        "cha_hybrid_v4_fix": r"\CHAlr",
        "cha_hybrid": r"CHA-Hybrid v1",
        "cha_hybrid_v2": r"CHA-Hybrid v2",
        "cha_hybrid_v3_tiny": r"\CHAs(tiny)",
        "cha_hybrid_v3_mini": r"\CHAs(mini)",
        "cha_hybrid_v3_base": r"\CHAs(base)",
        "cha_hybrid_v3_stl12": r"\CHAs($P{=}12$)",
        "cha_hybrid_v3_stl48": r"\CHAs($P{=}48$)",
        "cha_hybrid_v3_stl168": r"\CHAs($P{=}168$)",
        "chronos_zs": "Chronos-T5 ZS",
        "chronos_ft": "Chronos-T5 FT",
        "chronos_bolt_zs": "Chronos-Bolt",
        "timesfm_zs": "TimesFM",
        "moirai_zs": "MOIRAI",
        "ttm_zs": "TTM",
        "seasonal_naive": "Seasonal-Naive",
        "holt_winters": "Holt-Winters",
        "naive": "Naive",
        "arima": "ARIMA",
        "theta": "Theta",
        "farima": "FARIMA",
        "xgboost": "XGBoost",
        "lstm": "LSTM",
        "gru": "GRU",
        "tcn": "TCN",
        "nbeats": "N-BEATS",
        "dlinear": "DLinear",
        "patchtst": "PatchTST",
        "nhits": "N-HiTS",
        "tft": "TFT",
        "tide": "TiDE",
        "tsmixer": "TSMixer",
        # v3 ablation display names (already used in fig03)
        "cha_hybrid_v3_decomp_only": r"\CHAs{} decomp-only",
        "cha_hybrid_v3_global_only": "Chronos-Bolt only",
        "cha_hybrid_v3_fixed_alpha_0.5": r"\CHAs{} fixed-$\alpha{=}0.5$",
        "cha_hybrid_v3_altres_gru": r"\CHAs{} altres-GRU",
    }

    def _pretty(v: str) -> str:
        return DISPLAY.get(v, v.replace("_", r"\_"))

    # ----- bootstrap_ci_agg (Exp 1.1) -----
    src = TBL_IN / "bootstrap_ci_agg.csv"
    if _exists(src):
        df = pd.read_csv(src)
        # Filter to the proposed variants (v3 / v4 / decomp_only / global) +
        # the strongest baseline for compactness.
        focus = df[
            df["variant"].isin(
                [
                    "cha_hybrid_v3",
                    "cha_hybrid_v4",
                    "chronos_bolt_zs",
                    "timesfm_zs",
                    "moirai_zs",
                    "patchtst",
                    "nhits",
                    "lstm",
                    "xgboost",
                    "arima",
                    "farima",
                ]
            )
        ].copy()
        if not focus.empty:
            piv = focus.pivot_table(
                index=["dataset", "variant"],
                columns="horizon",
                values="rmse_mean",
                aggfunc="first",
            ).reset_index()

            def _render_leaderboard(horizon_subset, label, caption):
                cols = [c for c in piv.columns[2:] if c in horizon_subset]
                ln = [
                    "% auto-generated by pipeline/build_paper_tables.py",
                    r"\begin{table*}[t]",
                    r"\centering\small",
                    rf"\caption{{{caption}}}",
                    rf"\label{{tab:{label}}}",
                    r"\begin{tabular}{l l " + "r " * len(cols) + "}",
                    r"\toprule",
                    r"dataset & variant & "
                    + " & ".join(f"$h={h}$" for h in cols)
                    + r" \\",
                    r"\midrule",
                ]
                for ds, sub in piv.groupby("dataset"):
                    first = True
                    for _, r in sub.iterrows():
                        vals = " & ".join(
                            f"{r[h]:.3f}" if pd.notna(r[h]) else "—" for h in cols
                        )
                        ds_lbl = ds if first else ""
                        ln.append(f"{ds_lbl} & {_pretty(r['variant'])} & {vals} \\\\")
                        first = False
                    ln.append(r"\midrule")
                ln = ln[:-1]
                ln += [
                    r"\bottomrule",
                    r"\end{tabular}",
                    r"\end{table*}",
                ]
                return "\n".join(ln)

            # Split into two readable tables: short and long horizons.
            short_cap = (
                "Mean test-set RMSE (scaled) at short horizons "
                "$h \\in \\{1, 3, 6\\}$, averaged over five seeds; "
                "the lowest value per (dataset, horizon) is the better "
                "model. Long horizons $h \\in \\{12, 24\\}$ are in "
                "Table~\\ref{tab:main_leaderboard_long}; per-cell "
                "$95\\,\\%$ block-bootstrap CIs are released alongside "
                "the pipeline outputs."
            )
            long_cap = (
                "Mean test-set RMSE (scaled) at long horizons "
                "$h \\in \\{12, 24\\}$, companion to "
                "Table~\\ref{tab:main_leaderboard}."
            )
            _emit(
                _render_leaderboard([1, 3, 6], "main_leaderboard", short_cap),
                TBL_OUT / "main_leaderboard.tex",
            )
            _emit(
                _render_leaderboard([12, 24], "main_leaderboard_long", long_cap),
                TBL_OUT / "main_leaderboard_long.tex",
            )

    # ----- stationarity (Exp 4.4) -----
    src = TBL_IN / "stationarity.csv"
    if _exists(src):
        df = pd.read_csv(src)
        lines = [
            "% auto-generated by pipeline/build_paper_tables.py",
            r"\begin{table}[t]",
            r"\centering\small",
            r"\caption{Stationarity diagnostics on every (dataset, split) pair. "
            r"ADF reports the test statistic and $p$-value (null: unit root); "
            r"KPSS reports its statistic and $p$-value (null: stationary).}",
            r"\label{tab:stationarity}",
            r"\begin{tabular}{l l r r r r}",
            r"\toprule",
            r"dataset & split & $n$ & ADF stat & ADF $p$ & KPSS $p$ \\",
            r"\midrule",
        ]
        for _, r in df.iterrows():
            adf_p = f"{r['adf_pvalue']:.3g}" if pd.notna(r["adf_pvalue"]) else "—"
            adf_s = f"{r['adf_stat']:.2f}" if pd.notna(r["adf_stat"]) else "—"
            kp_p = f"{r['kpss_pvalue']:.3g}" if pd.notna(r["kpss_pvalue"]) else "—"
            lines.append(
                f"{r['dataset']} & {r['split']} & {int(r['n'])} & "
                f"{adf_s} & {adf_p} & {kp_p} \\\\"
            )
        lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
        _emit("\n".join(lines), TBL_OUT / "stationarity.tex")

    # ----- latency (Exp 1.4, optional) -----
    src = TBL_IN / "latency.csv"
    if _exists(src):
        df = pd.read_csv(src)
        if "status" in df.columns:
            df = df[df["status"] == "ok"]
        if not df.empty:
            piv = df.pivot_table(
                index=["variant"],
                columns=["device"],
                values="predict_per_window_ms",
                aggfunc="median",
            ).reset_index()
            lines = [
                "% auto-generated by pipeline/build_paper_tables.py",
                r"\begin{table}[t]",
                r"\centering\small",
                r"\caption{Median inference latency per test window (ms). "
                r"Across the full grid, on a single RTX 3060 GPU / Intel Xeon CPU.}",
                r"\label{tab:cost}",
                r"\begin{tabular}{l " + "r " * (piv.shape[1] - 1) + "}",
                r"\toprule",
                r"variant & " + " & ".join(piv.columns[1:]) + r" \\",
                r"\midrule",
            ]
            for _, r in piv.iterrows():
                vals = " & ".join(
                    f"{r[c]:.2f}" if pd.notna(r[c]) else "—" for c in piv.columns[1:]
                )
                lines.append(f"{_pretty(r['variant'])} & {vals} \\\\")
            lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
            _emit("\n".join(lines), TBL_OUT / "cost.tex")

    # ----- per-window v3-vs-Chronos-Bolt (Defense 5a) -----
    src = TBL_IN / "per_window_v3_vs_bolt_summary.csv"
    if _exists(src):
        df = pd.read_csv(src)
        if not df.empty:
            lines = [
                "% auto-generated by pipeline/build_paper_tables.py",
                r"\begin{table}[t]",
                r"\centering\small",
                r"\caption{Per-window outcome of \HybridV{} versus Chronos-Bolt "
                r"on the test split, classified with a 5\,\% tie band. "
                r"Even at globally tied mean RMSE, \HybridV{} strictly wins on "
                r"a substantial fraction of test windows.}",
                r"\label{tab:per_window_v3_vs_bolt}",
                r"\begin{tabular}{l r r r r}",
                r"\toprule",
                r"dataset & $h$ & v3 wins (\%) & tied (\%) & Bolt wins (\%) \\",
                r"\midrule",
            ]
            for _, r in df.iterrows():
                lines.append(
                    f"{r['dataset']} & {int(r['horizon'])} & "
                    f"{r['v3_wins_pct']:.1f} & {r['tied_pct']:.1f} & "
                    f"{r['bolt_wins_pct']:.1f} \\\\"
                )
            lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
            _emit("\n".join(lines), TBL_OUT / "per_window_v3_vs_bolt.tex")

    # ----- v3-vs-v4 (and v4_fix when available) -----
    src = TBL_IN / "v3_vs_v4.csv"
    if _exists(src):
        df = pd.read_csv(src)
        if not df.empty:
            lines = [
                "% auto-generated by pipeline/build_paper_tables.py",
                r"\begin{table}[t]",
                r"\centering\small",
                r"\caption{v4 (context-aware learned mixture) versus \HybridV{} "
                r"(horizon-adaptive scalar): mean test RMSE on the scaled "
                r"domain, averaged across five seeds. $\Delta$ is the "
                r"relative change in v4's favour (negative).  Vanilla v4 "
                r"overfits the small Abilene validation split; the v4-fix "
                r"variant in Sec.~\ref{sec:eval} addresses this.}",
                r"\label{tab:v3_vs_v4}",
                r"\begin{tabular}{l r r r r}",
                r"\toprule",
                r"dataset & $h$ & v3 RMSE & v4 RMSE & $\Delta$ (\%) \\",
                r"\midrule",
            ]
            for ds, sub in df.groupby("dataset"):
                first = True
                for _, r in sub.iterrows():
                    label = ds if first else ""
                    lines.append(
                        f"{label} & {int(r['horizon'])} & "
                        f"{r['v3_rmse_mean']:.3f} & {r['v4_rmse_mean']:.3f} & "
                        f"{r['rel_delta_pct']:+.2f} \\\\"
                    )
                    first = False
            lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
            _emit("\n".join(lines), TBL_OUT / "v3_vs_v4.tex")

    # ----- cross-dataset transfer (Exp 3.1, optional) -----
    src = TBL_IN / "cross_dataset_transfer.csv"
    if _exists(src):
        df = pd.read_csv(src)
        if not df.empty:
            mat = df.pivot_table(index="source", columns="target", values="rmse_scaled")
            lines = [
                "% auto-generated by pipeline/build_paper_tables.py",
                r"\begin{table}[t]",
                r"\centering\small",
                r"\caption{Cross-dataset transfer of \HybridV: rows = source "
                r"(trained on), columns = target (evaluated on). Diagonal = "
                r"in-domain RMSE; off-diagonals = plug-and-play.}",
                r"\label{tab:cross_dataset}",
                r"\begin{tabular}{l " + "r " * mat.shape[1] + "}",
                r"\toprule",
                r"source $\backslash$ target & " + " & ".join(mat.columns) + r" \\",
                r"\midrule",
            ]
            for src_ds, row in mat.iterrows():
                vals = " & ".join(f"{v:.3f}" if pd.notna(v) else "—" for v in row)
                lines.append(f"{src_ds} & {vals} \\\\")
            lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
            _emit("\n".join(lines), TBL_OUT / "cross_dataset.tex")

    print(f"\nDone. Tables in {TBL_OUT.resolve()}")


if __name__ == "__main__":
    with PhaseTimer(
        "build_paper_tables",
        notes="compile outputs/eval_v3/tables/*.csv → paper/tables/*.tex",
    ) as t:
        main()
        t.add_output("dir", str(TBL_OUT.resolve()))
