"""Build paper/tables/cross_dataset_alpha1.tex from the α=1 transfer CSV."""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from src.utils.runlog import PhaseTimer

OUT = Path("paper/tables")


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    df = pd.read_csv("outputs/eval_v3/tables/cross_dataset_transfer_alpha1.csv")
    mat = df.pivot_table(index="source", columns="target", values="rmse_alpha1")
    diag = np.diag(mat.values)
    norm = mat.values / diag[None, :]
    # Compose LaTeX
    cols = list(mat.columns)
    lines = [
        "% auto-generated by pipeline/build_alpha1_table.py",
        r"\begin{table*}[t]",
        r"\centering\small",
        r"\caption{Cross-dataset transfer of the \CHAs{} LSTM-residual head "
        r"with $\alpha = 1$ forced (i.e.\ decomposition-only forecast on the "
        r"target).  Cell value is RMSE relative to the target's own in-domain "
        r"$\alpha{=}1$ RMSE (diagonal $= 1.0$ by construction).  Off-diagonal "
        r"mean $1.013$ ($95\,\%$ CI $[0.996, 1.031]$); $4/20$ transfers "
        r"strictly beat the in-domain head.}",
        r"\label{tab:cross_dataset_alpha1}",
        r"\begin{tabular}{l " + " ".join(["r"] * len(cols)) + "}",
        r"\toprule",
        r"source $\backslash$ target & " + " & ".join(cols) + r" \\",
        r"\midrule",
    ]
    for i, src in enumerate(mat.index):
        cells = " & ".join(
            f"{norm[i, j]:.3f}" if np.isfinite(norm[i, j]) else "--"
            for j in range(len(cols))
        )
        lines.append(f"{src} & {cells} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
    out = OUT / "cross_dataset_alpha1.tex"
    out.write_text("\n".join(lines))
    print(f"wrote {out}")


if __name__ == "__main__":
    with PhaseTimer(
        "build_alpha1_table", notes="reviewer R2 C2: α=1 transfer table"
    ) as t:
        main()
        t.add_output("tex", str(OUT / "cross_dataset_alpha1.tex"))
