"""Stage A — Experiments 2.1 + 2.3: STL period sensitivity and
foundation-model size scaling.

Reads the trained metrics from Stage A's chronos-bolt-{tiny, mini,
small, base} runs and the STL period {12, 24, 48, 168} runs, then
produces:

  outputs/eval_v3/tables/foundation_size.csv
  outputs/eval_v3/tables/stl_period.csv
  outputs/figures/fig_sensitivity_foundation.pdf
  outputs/figures/fig_sensitivity_stl.pdf
  paper/tables/sensitivity_foundation.tex
  paper/tables/sensitivity_stl.tex
"""
from __future__ import annotations

import glob
import json
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from src.utils.runlog import PhaseTimer

OUT_TBL = Path("outputs/eval_v3/tables")
OUT_FIG = Path("outputs/figures")
PAPER_TBL = Path("paper/tables")
DATASETS = ["cesnet", "abilene", "geant", "nab_aws_cpu", "nab_twitter"]
HORIZONS = [1, 3, 6, 12, 24]


def collect_rmse(variant: str) -> dict:
    out = defaultdict(list)
    for f in glob.glob(f"outputs/metrics/*__{variant}__*.json"):
        try:
            m = json.load(open(f))
            if m.get("status") != "ok":
                continue
            out[(m["dataset"], int(m["horizon"]))].append(
                float(m["metrics_scaled"]["rmse"])
            )
        except Exception:
            continue
    return out


def main():
    OUT_TBL.mkdir(parents=True, exist_ok=True)
    OUT_FIG.mkdir(parents=True, exist_ok=True)
    PAPER_TBL.mkdir(parents=True, exist_ok=True)

    # --- Foundation-size scaling: tiny / mini / small / base ---
    size_map = {
        "tiny": "cha_hybrid_v3_tiny",
        "mini": "cha_hybrid_v3_mini",
        "small": "cha_hybrid_v3",  # the default
        "base": "cha_hybrid_v3_base",
    }
    size_rows = []
    for label, variant in size_map.items():
        rmse = collect_rmse(variant)
        for (ds, h), vs in rmse.items():
            size_rows.append(
                {
                    "size": label,
                    "variant": variant,
                    "dataset": ds,
                    "horizon": h,
                    "rmse_mean": float(np.mean(vs)),
                    "rmse_std": float(np.std(vs, ddof=1) if len(vs) > 1 else 0),
                    "n_seeds": len(vs),
                }
            )
    if size_rows:
        df_size = pd.DataFrame(size_rows)
        df_size.to_csv(OUT_TBL / "foundation_size.csv", index=False)
        print(f"foundation_size.csv: {len(df_size)} rows")

        # LaTeX table — mean across datasets, per horizon
        agg = df_size.groupby(["size", "horizon"]).rmse_mean.mean().unstack()
        # Re-order rows
        agg = agg.reindex(["tiny", "mini", "small", "base"])
        lines = [
            "% auto-generated by pipeline/expA_2_x_sensitivity.py",
            r"\begin{table}[t]",
            r"\centering\small",
            r"\caption{Foundation-expert size scaling: mean test RMSE "
            r"(across the five datasets) of \CHAs{} with chronos-bolt-"
            r"\{tiny, mini, small, base\} as the global expert.}",
            r"\label{tab:sensitivity_foundation}",
            r"\begin{tabular}{l " + "r " * len(agg.columns) + "}",
            r"\toprule",
            r"global expert & " + " & ".join(f"$h={h}$" for h in agg.columns) + r" \\",
            r"\midrule",
        ]
        for size, row in agg.iterrows():
            vals = " & ".join(f"{v:.3f}" if pd.notna(v) else "—" for v in row)
            lines.append(f"chronos-bolt-{size} & {vals} \\\\")
        lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
        (PAPER_TBL / "sensitivity_foundation.tex").write_text("\n".join(lines))
        print("wrote paper/tables/sensitivity_foundation.tex")

        # Figure: per-horizon RMSE curve per size
        fig, ax = plt.subplots(figsize=(6.5, 4))
        for size in ["tiny", "mini", "small", "base"]:
            if size in agg.index:
                row = agg.loc[size]
                ax.plot(row.index, row.values, marker="o", label=f"bolt-{size}")
        ax.set_xlabel("horizon $h$")
        ax.set_ylabel("mean test RMSE (scaled)")
        ax.set_title("Foundation-expert size scaling")
        ax.legend()
        ax.grid(True, alpha=0.3)
        fig.tight_layout()
        fig.savefig(OUT_FIG / "fig_sensitivity_foundation.pdf", bbox_inches="tight")
        fig.savefig(
            OUT_FIG / "fig_sensitivity_foundation.png", bbox_inches="tight", dpi=150
        )
        plt.close(fig)
        print("wrote fig_sensitivity_foundation.{pdf,png}")

    # --- STL period sensitivity: 12 / 24 / 48 / 168 ---
    stl_map = {
        12: "cha_hybrid_v3_stl12",
        24: "cha_hybrid_v3",
        48: "cha_hybrid_v3_stl48",
        168: "cha_hybrid_v3_stl168",
    }
    stl_rows = []
    for period, variant in stl_map.items():
        rmse = collect_rmse(variant)
        for (ds, h), vs in rmse.items():
            stl_rows.append(
                {
                    "period": period,
                    "variant": variant,
                    "dataset": ds,
                    "horizon": h,
                    "rmse_mean": float(np.mean(vs)),
                    "rmse_std": float(np.std(vs, ddof=1) if len(vs) > 1 else 0),
                    "n_seeds": len(vs),
                }
            )
    if stl_rows:
        df_stl = pd.DataFrame(stl_rows)
        df_stl.to_csv(OUT_TBL / "stl_period.csv", index=False)
        print(f"stl_period.csv: {len(df_stl)} rows")

        # Apples-to-apples: average every period only over the (dataset, horizon)
        # cells that ALL periods completed. Otherwise an incompletely-run period
        # (e.g. P=168) is averaged over an easier subset and its curve is
        # misleadingly low / not comparable to the others.
        _nper = df_stl["period"].nunique()
        _cellcov = df_stl.groupby(["dataset", "horizon"])["period"].nunique()
        _common = set(_cellcov[_cellcov == _nper].index)
        _ntot = df_stl.groupby(["dataset", "horizon"]).ngroups
        df_stl = df_stl[
            df_stl.apply(lambda r: (r["dataset"], r["horizon"]) in _common, axis=1)
        ].copy()
        print(
            f"[stl] common cells across all {_nper} periods: "
            f"{len(_common)}/{_ntot} (dropped incomplete cells for comparability)"
        )

        agg = df_stl.groupby(["period", "horizon"]).rmse_mean.mean().unstack()
        agg = agg.reindex(sorted(agg.index))
        lines = [
            "% auto-generated by pipeline/expA_2_x_sensitivity.py",
            r"\begin{table}[t]",
            r"\centering\small",
            r"\caption{STL period sensitivity: mean test RMSE (across the "
            r"five datasets) of \CHAs{} for different choices of the "
            r"STL seasonal period $P$.  Default $P=24$ (daily cycle).}",
            r"\label{tab:sensitivity_stl}",
            r"\begin{tabular}{r " + "r " * len(agg.columns) + "}",
            r"\toprule",
            r"$P$ & " + " & ".join(f"$h={h}$" for h in agg.columns) + r" \\",
            r"\midrule",
        ]
        for p, row in agg.iterrows():
            vals = " & ".join(f"{v:.3f}" if pd.notna(v) else "—" for v in row)
            lines.append(f"{int(p)} & {vals} \\\\")
        lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
        (PAPER_TBL / "sensitivity_stl.tex").write_text("\n".join(lines))
        print("wrote paper/tables/sensitivity_stl.tex")

        fig, ax = plt.subplots(figsize=(6.5, 4))
        for p in sorted(agg.index):
            row = agg.loc[p]
            ax.plot(row.index, row.values, marker="o", label=f"$P={p}$")
        ax.set_xlabel("horizon $h$")
        ax.set_ylabel("mean test RMSE (scaled)")
        ax.set_title("STL period sensitivity")
        ax.legend()
        ax.grid(True, alpha=0.3)
        fig.tight_layout()
        fig.savefig(OUT_FIG / "fig_sensitivity_stl.pdf", bbox_inches="tight")
        fig.savefig(OUT_FIG / "fig_sensitivity_stl.png", bbox_inches="tight", dpi=150)
        plt.close(fig)
        print("wrote fig_sensitivity_stl.{pdf,png}")


if __name__ == "__main__":
    with PhaseTimer(
        "expA_2_x_sensitivity",
        notes="STL period + foundation size scaling tables + figures",
    ) as t:
        main()
        t.add_output("foundation_csv", str(OUT_TBL / "foundation_size.csv"))
        t.add_output("stl_csv", str(OUT_TBL / "stl_period.csv"))
        t.add_output("foundation_pdf", str(OUT_FIG / "fig_sensitivity_foundation.pdf"))
        t.add_output("stl_pdf", str(OUT_FIG / "fig_sensitivity_stl.pdf"))
