"""3-way head-to-head: \\CHAs vs \\CHAl vs \\CHAlr.

Runs after Stage C trains the v4_fix variant.  Produces:

  outputs/eval_v3/tables/v3_v4_v4fix.csv
  paper/tables/v3_v4_v4fix.tex
  outputs/figures/fig_v3_v4_v4fix.pdf

The figure is a per-(dataset, horizon) grouped bar chart showing
the three RMSEs side-by-side; the table reports mean ± std plus
the relative improvement of each learned variant over the scalar
\\CHAs baseline.
"""
from __future__ import annotations

import glob
import json
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from src.utils.runlog import PhaseTimer

OUT_TBL = Path("outputs/eval_v3/tables")
OUT_FIG = Path("outputs/figures")
PAPER_TBL = Path("paper/tables")
DATASETS = ["cesnet", "abilene", "geant", "nab_aws_cpu", "nab_twitter"]
HORIZONS = [1, 3, 6, 12, 24]


def collect_rmse(variant: str) -> dict:
    out = defaultdict(list)
    for f in glob.glob(f"outputs/metrics/*__{variant}__*.json"):
        try:
            m = json.load(open(f))
            if m.get("status") != "ok":
                continue
            out[(m["dataset"], int(m["horizon"]))].append(
                float(m["metrics_scaled"]["rmse"])
            )
        except Exception:
            continue
    return out


def main():
    OUT_TBL.mkdir(parents=True, exist_ok=True)
    OUT_FIG.mkdir(parents=True, exist_ok=True)
    PAPER_TBL.mkdir(parents=True, exist_ok=True)

    v3 = collect_rmse("cha_hybrid_v3")
    v4 = collect_rmse("cha_hybrid_v4")
    v4fix = collect_rmse("cha_hybrid_v4_fix")

    if not v4fix:
        print("[3way] no v4_fix metrics yet — exiting cleanly")
        return

    rows = []
    for (ds, h), v3s in v3.items():
        v4s = v4.get((ds, h), [])
        v4f = v4fix.get((ds, h), [])
        if not v4f:
            continue
        v3m = float(np.mean(v3s))
        v4m = float(np.mean(v4s)) if v4s else np.nan
        v4fm = float(np.mean(v4f))
        rows.append(
            {
                "dataset": ds,
                "horizon": h,
                "v3_rmse": v3m,
                "v4_rmse": v4m,
                "v4fix_rmse": v4fm,
                "v4_rel": float(100 * (v4m - v3m) / v3m) if v4s else np.nan,
                "v4fix_rel": float(100 * (v4fm - v3m) / v3m),
                "v4fix_wins_vs_v3": v4fm < v3m,
                "v4fix_wins_vs_v4": v4fm < v4m if v4s else None,
            }
        )
    if not rows:
        return
    df = pd.DataFrame(rows).sort_values(["dataset", "horizon"])
    df.to_csv(OUT_TBL / "v3_v4_v4fix.csv", index=False)
    print(f"wrote v3_v4_v4fix.csv ({len(df)} cells)")

    n_v4fix_beats_v3 = int(df["v4fix_wins_vs_v3"].sum())
    n_v4fix_beats_v4 = int(df["v4fix_wins_vs_v4"].fillna(False).sum())
    total = len(df)
    print(f"v4_fix beats v3 in {n_v4fix_beats_v3}/{total} cells")
    print(f"v4_fix beats v4 in {n_v4fix_beats_v4}/{total} cells")
    print(f"median rel Δ (v4 - v3):     {df['v4_rel'].median():+.2f}%")
    print(f"median rel Δ (v4_fix - v3): {df['v4fix_rel'].median():+.2f}%")

    # Per-dataset summary on cells where v4 had worst regression
    worst = df.nlargest(3, "v4_rel")
    print("\nWorst v4 regressions vs v3 (should be fixed in v4_fix):")
    for _, r in worst.iterrows():
        print(
            f"  {r['dataset']:<14} h={int(r['horizon']):>2}  "
            f"v4: {r['v4_rel']:+.2f}%  v4_fix: {r['v4fix_rel']:+.2f}%"
        )

    # LaTeX table
    lines = [
        "% auto-generated by pipeline/expC_v3_v4_v4fix.py",
        r"\begin{table*}[t]",
        r"\centering\small",
        r"\caption{Three-way head-to-head of the proposed family on the "
        r"scaled-domain mean test RMSE (averaged across five seeds).  "
        r"$\Delta_v$ are relative changes versus \CHAs{} (negative = "
        r"improvement).}",
        r"\label{tab:v3_v4_v4fix}",
        r"\begin{tabular}{l r r r r r r}",
        r"\toprule",
        r"dataset & $h$ & \CHAs & \CHAl & $\Delta_{\CHAl}$ (\%) "
        r"& \CHAlr & $\Delta_{\CHAlr}$ (\%) \\",
        r"\midrule",
    ]
    for ds, sub in df.groupby("dataset"):
        first = True
        for _, r in sub.iterrows():
            label = ds if first else ""
            v4_str = f"{r['v4_rmse']:.3f}" if pd.notna(r["v4_rmse"]) else "—"
            v4_rel = f"{r['v4_rel']:+.2f}" if pd.notna(r["v4_rel"]) else "—"
            lines.append(
                f"{label} & {int(r['horizon'])} & {r['v3_rmse']:.3f} & "
                f"{v4_str} & {v4_rel} & {r['v4fix_rmse']:.3f} & "
                f"{r['v4fix_rel']:+.2f} \\\\"
            )
            first = False
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table*}"]
    (PAPER_TBL / "v3_v4_v4fix.tex").write_text("\n".join(lines))
    print("wrote paper/tables/v3_v4_v4fix.tex")

    # Grouped bar chart
    fig, ax = plt.subplots(figsize=(11, 4))
    cells = [f"{r['dataset']}·h={int(r['horizon'])}" for _, r in df.iterrows()]
    x = np.arange(len(cells))
    w = 0.27
    ax.bar(x - w, df["v3_rmse"], w, label="CHA-S")
    ax.bar(x, df["v4_rmse"], w, label="CHA-L")
    ax.bar(x + w, df["v4fix_rmse"], w, label="CHA-LR")
    ax.set_xticks(x)
    ax.set_xticklabels(cells, rotation=70, ha="right", fontsize=6)
    ax.set_ylabel("mean test RMSE (scaled)")
    ax.set_title("Three-way head-to-head: scalar vs learned vs regularised")
    ax.legend(loc="upper right")
    ax.grid(axis="y", alpha=0.3)
    fig.tight_layout()
    fig.savefig(OUT_FIG / "fig_v3_v4_v4fix.pdf", bbox_inches="tight")
    fig.savefig(OUT_FIG / "fig_v3_v4_v4fix.png", bbox_inches="tight", dpi=150)
    plt.close(fig)
    print("wrote fig_v3_v4_v4fix.{pdf,png}")


if __name__ == "__main__":
    with PhaseTimer(
        "expC_v3_v4_v4fix", notes="3-way head-to-head v3 vs v4 vs v4_fix"
    ) as t:
        main()
        t.add_output("csv", str(OUT_TBL / "v3_v4_v4fix.csv"))
        t.add_output("tex", str(PAPER_TBL / "v3_v4_v4fix.tex"))
        t.add_output("pdf", str(OUT_FIG / "fig_v3_v4_v4fix.pdf"))
