"""Edge-class real-system footprint of CHA-S (Paper A).

CHA-S is motivated for resource-constrained edge/IoT nodes. This script
measures its real deployment footprint under an edge-node compute envelope:
the forecaster is fitted offline (as it would be on a server), then pinned
to a SINGLE CPU core and streamed window-by-window (batch=1, the online
deployment mode), recording real per-window inference latency (p50/p95/p99)
and peak resident memory. Run optionally inside a systemd cgroup with one
CPU and a 2 GB memory cap (--cpus / MemoryMax) so the limits are enforced,
not just measured; we label this honestly as an edge-class container/core
envelope, not a literal Raspberry Pi.

Output: outputs/eval_v3/tables/edge_footprint.json + paper_a/tables/edge_footprint.tex
"""

from __future__ import annotations

import json
import os
import resource
import time
import warnings

warnings.filterwarnings("ignore")

import numpy as np

# Pin to a single CPU core (edge-class single-core envelope) BEFORE heavy work.
try:
    os.sched_setaffinity(0, {0})
    PINNED = True
except Exception:
    PINNED = False
# Keep math libraries single-threaded so the 1-core constraint is real.
for v in (
    "OMP_NUM_THREADS",
    "MKL_NUM_THREADS",
    "OPENBLAS_NUM_THREADS",
    "NUMEXPR_NUM_THREADS",
):
    os.environ[v] = "1"

from src.preprocessing import load_preprocessed
from src.preprocessing.windowing import WindowSet
from src.models import build_model
from src.training import MODEL_CONFIGS


def _slice(ws, i, j):
    return WindowSet(
        X=ws.X[i:j],
        y=ws.y[i:j],
        target_times=ws.target_times[i:j],
        split=ws.split,
        horizon=ws.horizon,
        lookback=ws.lookback,
    )


DS = "cesnet"
H = 6
N_STREAM = 300  # windows to stream (online, batch=1)


def main():
    match = next(((r, b) for r, v, b, s in MODEL_CONFIGS if v == "cha_hybrid_v3"), None)
    registry_name, base = match
    pp = load_preprocessed(DS)
    train_series = np.asarray(
        pp.split_scaled.train.to_numpy(), dtype=np.float32
    ).ravel()
    val_series = np.asarray(pp.split_scaled.val.to_numpy(), dtype=np.float32).ravel()
    test = pp.windows[H]["test"]
    train_w = pp.windows[H]["train"]
    val_w = pp.windows[H].get("val")

    model = build_model(registry_name, horizon=H, hparams=base, seed=42, device="cpu")
    # Offline fit (server-side; not part of the edge latency budget).
    model.fit(train_w, val_w, train_series=train_series, val_series=val_series)

    # Warm up one inference, then stream batch=1 under the single-core pin.
    _ = model.predict(_slice(test, 0, 1))
    n = min(N_STREAM, len(test.X))
    lat = np.empty(n)
    for i in range(n):
        w = _slice(test, i, i + 1)
        t0 = time.perf_counter()
        _ = model.predict(w)
        lat[i] = (time.perf_counter() - t0) * 1000.0  # ms

    peak_rss_mb = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024.0
    ncores = len(os.sched_getaffinity(0))
    stats = {
        "dataset": DS,
        "horizon": H,
        "pinned_single_core": PINNED,
        "cores_visible": ncores,
        "n_windows": int(n),
        "p50_ms": round(float(np.percentile(lat, 50)), 2),
        "p95_ms": round(float(np.percentile(lat, 95)), 2),
        "p99_ms": round(float(np.percentile(lat, 99)), 2),
        "mean_ms": round(float(lat.mean()), 2),
        "throughput_win_per_s": round(float(1000.0 / lat.mean()), 1),
        "peak_rss_mb": round(float(peak_rss_mb), 1),
    }
    os.makedirs("outputs/eval_v3/tables", exist_ok=True)
    json.dump(stats, open("outputs/eval_v3/tables/edge_footprint.json", "w"), indent=2)

    tex = [
        "% Auto-generated by pipeline/expR7_edge_footprint.py",
        "\\begin{table}[!ht]\\centering\\footnotesize",
        "\\caption{Edge-class real-system footprint of \\HybridV{} on "
        "CESNET-TS24 ($h{=}6$). The forecaster is fitted offline, then pinned "
        "to a single CPU core with single-threaded math libraries (a "
        "Raspberry-Pi-4-class compute envelope) and streamed window by window "
        "in the online batch-of-one mode. We report real per-window inference "
        "latency and peak resident memory over "
        + str(stats["n_windows"])
        + " streamed windows.}",
        "\\label{tab:edge_footprint}",
        "\\begin{tabular}{l c}",
        "\\toprule",
        "Metric (single core, batch$=$1) & Value \\\\",
        "\\midrule",
        f"Median per-window latency & ${stats['p50_ms']}$\\,ms \\\\",
        f"95th-percentile latency & ${stats['p95_ms']}$\\,ms \\\\",
        f"99th-percentile latency & ${stats['p99_ms']}$\\,ms \\\\",
        f"Sustained throughput & ${stats['throughput_win_per_s']}$ windows/s \\\\",
        f"Peak resident memory & ${stats['peak_rss_mb']}$\\,MB \\\\",
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
    ]
    open("paper_a/tables/edge_footprint.tex", "w").write("\n".join(tex))
    print(json.dumps(stats, indent=2))
    print("wrote paper_a/tables/edge_footprint.tex")


if __name__ == "__main__":
    main()
